### ISSUE TITLE
Give ability to change pic links

### ISSUE THREAD

**Issue by numfin** [GeorgePlotnikov/ImageBlendingAlgorithms#10]
requesting feature for ya! gl
Make it possible for user to change pic list
![image](https://user-images.githubusercontent.com/8134947/34747198-3924eb70-f5a8-11e7-8e45-230f34aba51d.png)

**Comment by 0xGeorgii** [comment]
@numfin absolutely it makes sense, should be added after finishing #1 not to overlay the same functionality
