### ISSUE TITLE
Create unit test project

### ISSUE THREAD

**Issue by 0xGeorgii** [GeorgePlotnikov/ImageBlendingAlgorithms#2]

**Comment by Blackaist** [comment]
wasap

**Comment by Blackaist** [comment]
Как мне сюда добавить возможность создания под .Net Core?
![image](https://user-images.githubusercontent.com/17519552/34633003-35b79418-f28a-11e7-8525-46ca375849f6.png)

**Comment by 0xGeorgii** [comment]
@Blackaist ,  You should add dotnet core cross platform development add on to your VS. like described [here](https://www.microsoft.com/net/learn/get-started/windows) "Get editor"

**Comment by Blackaist** [comment]
sumR = colors.Sum(c=>c.R),
sumG = colors.Sum(c=>c.G)
sumB = colors.Sum(c=>c.R);
Все верно? Разве в третьей строчке не ошибка?

**Comment by 0xGeorgii** [comment]
@Blackaist, yes, looks like a type that was done during migration to the dotnet core. Will fix it.

**Comment by GeorgePlotnikov** [comment]
[done](https://github.com/GeorgePlotnikov/ImageBlendingAlgorithms/pull/7)

**Comment by 0xGeorgii** [comment]
#7
